basePath: /
consumes:
- application/json
definitions:
  AdvertisingAdd:
    description: easyjson:json
    properties:
      cost:
        format: int64
        type: integer
        x-go-name: Cost
      description:
        maxLength: 1000
        type: string
        x-go-name: Description
      name:
        maxLength: 200
        type: string
        x-go-name: Name
      photos:
        items:
          type: string
        maxLength: 3
        type: array
        x-go-name: Photos
    type: object
    x-go-package: github.com/Kostikans/AvitoTechadvertising/internal/app/advertising/model
  AdvertisingID:
    description: easyjson:json
    properties:
      advertisingID:
        format: int64
        type: integer
        x-go-name: AdvID
    type: object
    x-go-package: github.com/Kostikans/AvitoTechadvertising/internal/app/advertising/model
  AdvertisingList:
    description: easyjson:json
    properties:
      links:
        $ref: '#/definitions/Links'
      list:
        items:
          $ref: '#/definitions/AdvertisingListItem'
        type: array
        x-go-name: List
      page:
        $ref: '#/definitions/Page'
    type: object
    x-go-package: github.com/Kostikans/AvitoTechadvertising/internal/app/advertising/model
  AdvertisingListItem:
    description: easyjson:json
    properties:
      cost:
        format: int64
        type: integer
        x-go-name: Cost
      mainPhoto:
        type: string
        x-go-name: MainPhoto
      name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/Kostikans/AvitoTechadvertising/internal/app/advertising/model
  ErrorRequestWrap:
    properties:
      code:
        format: int64
        type: integer
        x-go-name: Code
      error:
        type: string
        x-go-name: Err
    type: object
    x-go-package: github.com/Kostikans/AvitoTechadvertising/docs
  GetAdvertising:
    properties:
      cost:
        format: int64
        type: integer
        x-go-name: Cost
      description:
        description: optional
        type: string
        x-go-name: Description
      mainPhoto:
        type: string
        x-go-name: MainPhoto
      name:
        type: string
        x-go-name: Name
      photos:
        description: optional
        items:
          type: string
        type: array
        x-go-name: Photos
    type: object
    x-go-package: github.com/Kostikans/AvitoTechadvertising/docs
  Links:
    description: easyjson:json
    properties:
      last:
        type: string
        x-go-name: Last
      next:
        type: string
        x-go-name: NextUrl
      prev:
        type: string
        x-go-name: PrevUrl
    type: object
    x-go-package: github.com/Kostikans/AvitoTechadvertising/internal/app/advertising/model
  Page:
    description: easyjson:json
    properties:
      currentPage:
        format: int64
        type: integer
        x-go-name: CurrentPage
      lastPage:
        format: int64
        type: integer
        x-go-name: LastPage
      perPage:
        format: int64
        type: integer
        x-go-name: PerPage
    type: object
    x-go-package: github.com/Kostikans/AvitoTechadvertising/internal/app/advertising/model
info:
  description: Swagger spec.
  title: Golang service API for Avito
  version: 1.0.0
paths:
  /api/v1/advertising:
    get:
      operationId: ListAdvertising
      parameters:
      - description: '"cost" or "created"'
        in: query
        name: sort
        type: string
        x-go-name: Sort
      - in: query
        name: desc
        type: boolean
        x-go-name: Desc
      - description: by default 1
        format: int64
        in: query
        name: page
        type: integer
        x-go-name: Page
      responses:
        "200":
          $ref: '#/responses/ListAdvertising'
        "400":
          $ref: '#/responses/badrequest'
      tags:
      - advertising
    post:
      operationId: AddAdvertising
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/AdvertisingAdd'
      responses:
        "200": {}
        "201":
          $ref: '#/responses/AddAdvertising'
        "400":
          $ref: '#/responses/badrequest'
      tags:
      - advertising
  /api/v1/advertising/{id}:
    get:
      operationId: GetAdvertising
      parameters:
      - format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      - description: description or photos, or both with ',' splitter; example(description,photos)
        in: query
        name: fields
        type: string
        x-go-name: Fields
      responses:
        "200":
          $ref: '#/responses/GetAdvertising'
        "400":
          $ref: '#/responses/badrequest'
        "404":
          $ref: '#/responses/notfound'
      tags:
      - advertising
produces:
- application/json
responses:
  AddAdvertising:
    schema:
      properties:
        code:
          format: int64
          type: integer
          x-go-name: Code
        data:
          $ref: '#/definitions/AdvertisingID'
      type: object
  GetAdvertising:
    headers:
      Body:
        description: 'in: Body'
    schema:
      properties:
        code:
          format: int64
          type: integer
          x-go-name: Code
        data:
          $ref: '#/definitions/GetAdvertising'
      type: object
  ListAdvertising:
    headers:
      Body:
        description: 'in: Body'
    schema:
      properties:
        code:
          format: int64
          type: integer
          x-go-name: Code
        data:
          $ref: '#/definitions/AdvertisingList'
      type: object
  badrequest:
    description: invalid json or get parameters
    schema:
      $ref: '#/definitions/ErrorRequestWrap'
  notfound:
    description: data doesn't exist
    schema:
      $ref: '#/definitions/ErrorRequestWrap'
schemes:
- http
swagger: "2.0"
