// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package advertising_mock is a generated GoMock package.
package advertising_mock

import (
	advertisingModel "github.com/Kostikans/AvitoTechadvertising/internal/app/advertising/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddAdvertising mocks base method
func (m *MockRepository) AddAdvertising(advertising advertisingModel.AdvertisingAdd) (advertisingModel.AdvertisingID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAdvertising", advertising)
	ret0, _ := ret[0].(advertisingModel.AdvertisingID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAdvertising indicates an expected call of AddAdvertising
func (mr *MockRepositoryMockRecorder) AddAdvertising(advertising interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAdvertising", reflect.TypeOf((*MockRepository)(nil).AddAdvertising), advertising)
}

// GetAdvertising mocks base method
func (m *MockRepository) GetAdvertising(advertisingID int, fields string) (advertisingModel.Advertising, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertising", advertisingID, fields)
	ret0, _ := ret[0].(advertisingModel.Advertising)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvertising indicates an expected call of GetAdvertising
func (mr *MockRepositoryMockRecorder) GetAdvertising(advertisingID, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertising", reflect.TypeOf((*MockRepository)(nil).GetAdvertising), advertisingID, fields)
}

// ListAdvertising mocks base method
func (m *MockRepository) ListAdvertising(field, desc string) (advertisingModel.AdvertisingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdvertising", field, desc)
	ret0, _ := ret[0].(advertisingModel.AdvertisingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdvertising indicates an expected call of ListAdvertising
func (mr *MockRepositoryMockRecorder) ListAdvertising(field, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdvertising", reflect.TypeOf((*MockRepository)(nil).ListAdvertising), field, desc)
}

// CheckAdvertisingExist mocks base method
func (m *MockRepository) CheckAdvertisingExist(advertisingID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAdvertisingExist", advertisingID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAdvertisingExist indicates an expected call of CheckAdvertisingExist
func (mr *MockRepositoryMockRecorder) CheckAdvertisingExist(advertisingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAdvertisingExist", reflect.TypeOf((*MockRepository)(nil).CheckAdvertisingExist), advertisingID)
}
